spring:
  redis:
    lettuce:
      pool:
        max-active: '7 '
        max-idle: '7'
        min-idle: '2'
        max-wait: -1ms
      shutdown-timeout: 200ms
    host: localhost
    port: '6379'
  datasource:
    password: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    testOnBorrow: 'true'
    url: jdbc:postgresql://localhost:5432/foodie
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
